/// @file hrtf_trim.cpp
/// @brief Emit an order-trimmed (optionally single-projection) drop-in replacement
///        for include/ambitap/math/binaural/hrtf_data.h, for flash-constrained
///        embedded deployments. See docs/EMBEDDED.md for the size table.
///
///        Usage: hrtf_trim --order N [--projection ls|magls|both] --out FILE
///
///        The emitted header defines the same symbols as the full dataset, so it
///        drops in via the include path with no code changes. With a single
///        projection the other projection's names become references to the kept
///        arrays: set_projection() then has no audible effect — chosen so the
///        renderer still compiles and flash stores one copy.
// SPDX-License-Identifier: MIT
// Copyright 2026 Timothy Place.

#include <cstdio>
#include <cstring>
#include <string>

#include <ambitap/math/binaural/hrtf_data.h>

namespace {

    void emit_array(std::FILE* f, const char* name, const float (*table)[ambitap::builtin_hrtf_length], int channels) {
        std::fprintf(f, "inline constexpr float %s[%d][%zu] = {\n", name, channels, ambitap::builtin_hrtf_length);
        for (int ch = 0; ch < channels; ++ch) {
            std::fprintf(f, "    { // ACN %d\n", ch);
            for (size_t i = 0; i < ambitap::builtin_hrtf_length; ++i) {
                if (i % 8 == 0)
                    std::fprintf(f, "       ");
                std::fprintf(f, " %.8ef,", static_cast<double>(table[ch][i]));
                if (i % 8 == 7)
                    std::fprintf(f, "\n");
            }
            std::fprintf(f, "    },\n");
        }
        std::fprintf(f, "};\n\n");
    }

} // namespace

int main(int argc, char** argv) {
    int         order      = -1;
    std::string projection = "both";
    std::string out_path;

    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--order" && i + 1 < argc) {
            order = std::atoi(argv[++i]);
        }
        else if (arg == "--projection" && i + 1 < argc) {
            projection = argv[++i];
        }
        else if (arg == "--out" && i + 1 < argc) {
            out_path = argv[++i];
        }
        else {
            std::fprintf(stderr, "unknown argument: %s\n", arg.c_str());
            return 1;
        }
    }

    if (order < 1 || order > ambitap::builtin_hrtf_order || out_path.empty()
        || (projection != "ls" && projection != "magls" && projection != "both")) {
        std::fprintf(stderr,
                     "usage: hrtf_trim --order N (1..%d) [--projection ls|magls|both] "
                     "--out FILE\n",
                     ambitap::builtin_hrtf_order);
        return 1;
    }

    const int channels = (order + 1) * (order + 1);

    std::FILE* f = std::fopen(out_path.c_str(), "w");
    if (!f) {
        std::fprintf(stderr, "cannot open %s\n", out_path.c_str());
        return 1;
    }

    const bool   ls    = projection != "magls";
    const bool   magls = projection != "ls";
    const size_t bytes = static_cast<size_t>(channels) * ambitap::builtin_hrtf_length * sizeof(float) * 2
                         * ((ls ? 1u : 0u) + (magls ? 1u : 0u));

    std::fprintf(f,
                 "/// AmbiTap: target-independent ambisonics library\n"
                 "/// TRIMMED built-in SH-domain HRTF dataset — generated by tools/hrtf_trim from\n"
                 "/// the full embedded order-%d MIT KEMAR dataset (see the original hrtf_data.h\n"
                 "/// for provenance and attribution; the KEMAR data is credited to W. G. Gardner\n"
                 "/// and K. D. Martin, MIT Media Lab TR #280, 1994).\n"
                 "///\n"
                 "/// order %d, projection %s — %zu bytes of table data.\n"
                 "/// Drop-in replacement: put this file ahead of the stock header on the\n"
                 "/// include path as ambitap/math/binaural/hrtf_data.h.\n"
                 "%s"
                 "\n"
                 "#ifndef AMBITAP_MATH_HRTF_DATA_H\n"
                 "#define AMBITAP_MATH_HRTF_DATA_H\n"
                 "\n"
                 "#include <cstddef>\n"
                 "\n"
                 "namespace ambitap {\n"
                 "\n"
                 "inline constexpr int    builtin_hrtf_order       = %d;\n"
                 "inline constexpr size_t builtin_hrtf_channels    = %d;\n"
                 "inline constexpr size_t builtin_hrtf_length      = %zu;\n"
                 "inline constexpr float  builtin_hrtf_sample_rate = %.1ff;\n"
                 "\n",
                 ambitap::builtin_hrtf_order, order, projection.c_str(), bytes,
                 projection == "both" ? ""
                                      : "///\n/// SINGLE-PROJECTION BUILD: the omitted projection's symbols alias the\n"
                                        "/// kept arrays, so binaural_renderer::set_projection() has NO effect.\n",
                 order, channels, ambitap::builtin_hrtf_length, static_cast<double>(ambitap::builtin_hrtf_sample_rate));

    if (ls) {
        emit_array(f, "builtin_hrtf_left", ambitap::builtin_hrtf_left, channels);
        emit_array(f, "builtin_hrtf_right", ambitap::builtin_hrtf_right, channels);
    }
    if (magls) {
        emit_array(f, "builtin_hrtf_magls_left", ambitap::builtin_hrtf_magls_left, channels);
        emit_array(f, "builtin_hrtf_magls_right", ambitap::builtin_hrtf_magls_right, channels);
    }
    if (!magls) {
        std::fprintf(f, "inline constexpr auto& builtin_hrtf_magls_left  = builtin_hrtf_left;\n"
                        "inline constexpr auto& builtin_hrtf_magls_right = builtin_hrtf_right;\n\n");
    }
    if (!ls) {
        std::fprintf(f, "inline constexpr auto& builtin_hrtf_left  = builtin_hrtf_magls_left;\n"
                        "inline constexpr auto& builtin_hrtf_right = builtin_hrtf_magls_right;\n\n");
    }

    std::fprintf(f, "} // namespace ambitap\n\n#endif // AMBITAP_MATH_HRTF_DATA_H\n");
    std::fclose(f);

    std::fprintf(stderr, "wrote %s: order %d, projection %s, %zu bytes of tables\n", out_path.c_str(), order,
                 projection.c_str(), bytes);
    return 0;
}
