#!/usr/bin/env python3
"""Generate the seed-11 FDN noise/sign tables for dsp::room.

dsp::room replicates the FDN tail architecture verified by
notebooks/room_verification.ipynb against the R1-R10 gates in
docs/PERCEPTUAL-VERIFICATION.md. That prototype (notebooks/room_model.py)
draws every random quantity from one numpy Generator (PCG64) seeded with the
committed seed 11 — the seed is part of the parameterization, and gate R10
byte-compares two renders. Reproducing numpy's PCG64 stream *and* its
ziggurat Gaussian sampler bit-for-bit in C++ is not reasonable, so the raw
draws are baked here instead (the hrtf_data.h approach) and everything
DERIVED from them — octave-band splitting, decay shaping, normalization,
FIR fitting — is computed by dsp::room at run time from its parameters.

Baked data, in the prototype's exact draw order (room_model.render_fdn_tail):

  1. feedback matrix signs   s1, s2 = rng.choice([-1, 1], 16) twice
                             (feedback = diag(s1) . H/4 . diag(s2))
  2. output matrix signs     s3, s4 likewise
                             (out_mix = (diag(s3) . H/4 . diag(s4))[:channels])
  3. input-burst noise       16 lines x rng.standard_normal(2560)
                             (raw, UNSHAPED: dsp::room band-splits and applies
                             the parameterized per-octave decay envelopes)

Regeneration (only needed if the seed or FDN topology changes — both are
part of the verified parameterization, so expect to re-run the verification
notebook too):

    python3 scripts/generate_room_data.py

It rewrites include/ambitap/dsp/room_data.h.

Copyright 2026 Timothy Place. MIT License.
"""

import pathlib

import numpy as np

SEED = 11
LINES = 16
BURST_LEN = 2560

HEADER = pathlib.Path(__file__).resolve().parent.parent / "include/ambitap/dsp/room_data.h"


def emit_signs(lines, name, signs):
    body = ", ".join(f"{s:+.1f}f" for s in signs)
    lines.append(f"inline constexpr float {name}[room_data_lines] = {{{body}}};")
    lines.append("")


def main():
    rng = np.random.default_rng(SEED)
    s1 = rng.choice([-1.0, 1.0], size=LINES)
    s2 = rng.choice([-1.0, 1.0], size=LINES)
    s3 = rng.choice([-1.0, 1.0], size=LINES)
    s4 = rng.choice([-1.0, 1.0], size=LINES)
    noise = np.stack([rng.standard_normal(BURST_LEN) for _ in range(LINES)])

    lines = [
        "/// AmbiTap: target-independent ambisonics library",
        "/// Seed-11 FDN noise/sign tables for dsp::room.",
        f"/// Auto-generated by scripts/generate_room_data.py (numpy PCG64, seed {SEED});",
        "/// see that script for why the draws are baked rather than re-derived.",
        "/// Timothy Place",
        "/// Copyright 2026 Timothy Place.",
        "",
        "#ifndef AMBITAP_DSP_ROOM_DATA_H",
        "#define AMBITAP_DSP_ROOM_DATA_H",
        "",
        "#include <cstddef>",
        "",
        "namespace ambitap {",
        "",
        f"inline constexpr int    room_data_seed         = {SEED};",
        f"inline constexpr size_t room_data_lines        = {LINES};",
        f"inline constexpr size_t room_data_burst_length = {BURST_LEN};",
        "",
        "/// Diagonal sign conjugations of the (Sylvester) Hadamard mixing",
        "/// matrices: feedback = diag(rows) . H/sqrt(16) . diag(cols).",
    ]
    emit_signs(lines, "room_feedback_sign_rows", s1)
    emit_signs(lines, "room_feedback_sign_cols", s2)
    lines.append("/// Same construction for the line-to-SH output distribution")
    lines.append("/// (rows 0..channels-1 are used at render order <= 3).")
    emit_signs(lines, "room_output_sign_rows", s3)
    emit_signs(lines, "room_output_sign_cols", s4)

    lines.append("/// Raw unit-variance noise draws for the per-line input bursts,")
    lines.append("/// indexed room_noise[line][sample]. Unshaped: dsp::room applies the")
    lines.append("/// octave-band split, decay envelopes, and unit-energy normalization")
    lines.append("/// from its runtime RT60 parameterization.")
    lines.append("inline constexpr float room_noise[room_data_lines][room_data_burst_length] = {")
    for i in range(LINES):
        lines.append(f"    {{ // line {i}")
        row = noise[i].astype(np.float32)
        for start in range(0, BURST_LEN, 8):
            chunk = ", ".join(f"{v:+.8e}f" for v in row[start:start + 8])
            lines.append(f"        {chunk},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace ambitap")
    lines.append("")
    lines.append("#endif // AMBITAP_DSP_ROOM_DATA_H")
    lines.append("")

    HEADER.write_text("\n".join(lines))
    print(f"wrote {HEADER} ({HEADER.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
